### PR TITLE
centered Subscribe button

### PR DESCRIPTION
**Pull request by STashakkori**

### CODE REVIEW

**Comment by STashakkori** [comment]
Fixes #1621

**Comment by Deborah-Digges** [comment]
Hi @STashakkori, thank you for this contribution! 

It looks great in Firefox:
screenshot from 2015-04-19 14 58 38

However, in Chrome, the center aligned button looks a little unnatural:
screenshot from 2015-04-19 14 58 52

Would it be possible to make it look like this:

**Comment by STashakkori** [comment]
Sure Deborah,

I can do that. Will do so as soon as I get home from Boston tonight.

Best,
Sina

On Sun, Apr 19, 2015 at 5:57 AM, Deborah Digges <notifications@github.com>
wrote:

> Hi @STashakkori <https://github.com/STashakkori>, thank you for this
> contribution!
>
> It looks great in Firefox:
> [image: screenshot from 2015-04-19 14 58 38]
> <https://cloud.githubusercontent.com/assets/3866405/7218928/f5ccb480-e6a4-11e4-8b32-7c22dc61ba89.png>
>
> However, in Chrome, the center aligned button looks a little unnatural:
> [image: screenshot from 2015-04-19 14 58 52]
> <https://cloud.githubusercontent.com/assets/3866405/7218941/8f09a3e2-e6a5-11e4-954d-e3681b448dcb.png>
>
> Would it be possible to make it look like this:
> [Uploading Screenshot from 2015-04-19 15:14:29.png . . .]()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhatch/oh-mainline/pull/1624#issuecomment-94257217>
> .[image: Web Bug from
> https://github.com/notifications/beacon/AED4a2koIxXU3wri6-UKBQRkkhXwjDA2ks5oA3OGgaJpZM4EDFpB.gif]
>



-- 
Sina Tashakkori, B.S.
UNC Chapel Hill
Appalachian State Univ.

**Comment by willingc** [comment]
@Deborah-Digges Very thoughtful review with pictures :)

@STashakkori Thank you for working on this issue/PR :)

**Comment by Deborah-Digges** [comment]
@STashakkori,
It looks like this issue has recently been fixed  by https://github.com/openhatch/oh-mainline/pull/1644. I'm going to close this PR as the issue is now resolved.

Thank you for your contribution, nevertheless!

**Comment by STashakkori** [comment]
That's cool, i fixed that weeks ago but ok.

**Pull request closed without merging**
