### PR TITLE
Add ALT text to images on homepage

### LINKED ISSUE #1446: Add ALT text to images on homepage
Per http://wave.webaim.org/report#/https://openhatch.org/ , there a number of accessibility issues with the OpenHatch front page.

(If you're new to accessibility, here's the one-sentence Wikipedia summary -- "Accessibility is the degree to which a product, device, service, or environment is available to as many people as possible" -- and here's an article with way more information: http://en.wikipedia.org/wiki/Accessibility )

Right now, the webaim report indicates the following problems with the OpenHatch front page:

* 10 missing ALT text problems

* 11 "redundant links" (click around within webaim to learn more, but it seems to me that the best fix is to give some images an ALT text of the empty string)

There is also a "Skipped heading level" problem, but I'd prefer to see that addressed in a separate pull request, since I think the fix will be more complicated.

Relevant facts:

* The default user profile photo is our mascot, Sufjan -- https://openhatch.org/wiki/Sufjan

* To get the OpenHatch code on your computer, see http://openhatch.readthedocs.org/en/latest/getting_started/installation.html

* The front page is powered by the https://github.com/openhatch/oh-mainline/blob/master/mysite/base/templates/base/landing.html template file.

### PR DESCRIPTION
**Pull request by eeshangarg**
Closes #1446. This PR adds alt text to the image of our mascot on our homepage. And also adds alt text to the image in [this file] (https://github.com/openhatch/oh-mainline/blob/master/mysite/base/templates/base/wannahelp-in-feed.html), which was not addressed by #1638. :-)

Please let me know if this needs further work. I would love to work on it!

Thanks & regards,
Eeshan Garg

### CODE REVIEW

**Comment by phildini** [comment]
Hey Eeshan! Thanks for submitting, this looks good! Would you feel confident adjusting the "Profile Picture for User" to something like "Profile picture for {{ person.name }}"? I don't know what the correct variable would be here, unfortunately, so it might require a little testing and digging on your part. 

If you'd rather not, that's totally fine - let me know and I'll merge as-is.

Thanks again!

**Comment by eeshangarg** [comment]
Hi @phildini! Thanks for the review! 

I would love to do that. I'll take a deeper look at the code and let you know how it goes. Meanwhile, I think we should not merge this PR. If we can implement what you just proposed, I think that would be amazing!  I'll post here if I have any questions or comments. :-)

Warm regards,
Eeshan Garg

**Comment by eeshangarg** [comment]
Hello @phildini!

I just added the functionality that you proposed. See [this method] (https://github.com/openhatch/oh-mainline/blob/master/mysite/profile/models.py#L395) of the [Person] (https://github.com/openhatch/oh-mainline/blob/master/mysite/profile/models.py#L89) class. I could not find any way of testing my changes, since when I run the development server locally on my computer, the blog feed is empty. So I don't know if this will work, I just read the code and tried to make a logical guess about how this could be implemented. If you find a way to test this, please let me know. Also, if this needs further work, again, I would love to work on it. :-)

Thanks & regards,
Eeshan Garg

**Comment by phildini** [comment]
Awesome! Thank you for updating. Two things:

1) I wonder if get_full_name_or_username() is the better choice here?
2) I'm /cc paulproteus for his ideas on how one of us could test the blog post feed. Create a blog post in the dev env? Is that possible?

**Comment by eeshangarg** [comment]
Hi @phildini, @paulproteus! I made a mistake in my previous comment. I said "blog feed" when I should have said "recent site activity feed". I need a way to test the recent site activity feed. Sorry about that! :-)

**Comment by paulproteus** [comment]
The recent site activity feed should be manually-testable by causing some
activity on the site that the recent activity feed tracks, for what it's
worth! Like going to a project page and "answering a Question".​

**Comment by willingc** [comment]
Also @eeshangarg @phildini @paulproteus 
FWIW looks like [get_full_name_and_username is tested](https://github.com/openhatch/oh-mainline/blob/db98e6f50c08819eacfbb60c617a4f7eb4ae4bd4/mysite/profile/tests.py#L99) while get_full_name_or_username is not.

**Comment by eeshangarg** [comment]
I just tested my changes like @paulproteus advised me to and they work. :-)

**Comment by phildini** [comment]
LGTM!

**Pull request merged**
