### PR TITLE
Fix for issue #1680 [Removed cookie 'openid_provider] [Removed 'demo.html']

### PR DESCRIPTION
**Pull request by waseem18**
Removed the cookie 'openid_provider' (and cookie related operations like 'setCookie' and 'readCookie') which was responsible for the issue #1680

### CODE REVIEW

**Comment by paulproteus** [comment]
Hi there,

Thanks for submitting this! This looks like a good start.

I recommend deleting even more code, for what it's worth. If the `readCookie()` function isn't called anymore, delete it. Keep deleting things until there's nothing left to delete. A line deleted is a line tested.

If you're interested in that, great! If not, or if you don't answer after a week or so, then we could merge this as-is.

When it's ready for merge, if possible, could you freshly rebase this to avoid the unnecessary merge commit? I believe @willingc can provide good links on how to do that.

I won't be able to provide much more feedback over the next week due to some travel, but I hope someone else can (e.g. @ehashman) and then we can merge this!

**Comment by waseem18** [comment]
Hello @paulproteus ,

I have thoroughly checked the code and have removed all possible operations related to cookies. I have also tested it successfully. I feel that the code is clean enough to be merged. :+1: 

@ehashman @willingc  Can you please help me out in the below issue.

I feel that this file (https://github.com/ehashman/oh-mainline/blob/master/mysite/static/openid/demo.html) is of no use to OH. So it would be better if we can delete it and keep everything clean. What do you say about this?

**Comment by paulproteus** [comment]
A line deleted is a line tested. Go for it, w/r/t deleting demo.html.

**Comment by waseem18** [comment]
Hi @paulproteus 

In this PR, I have tried to resolve the bug #1680 and to keep the repo clean I have also removed the file 'demo.html'.

Hope this PR gets merged :)

**Comment by ehashman** [comment]
I'll do some testing of this as soon as I get a chance, so it's in my ballpark now. Please ping me if I don't get to this in a timely manner.

**Comment by ehashman** [comment]
I've tested this and I'm not seeing the same issue I was having before, and login seems to work fine, so since the tests are passing I'm going to go ahead and merge this. Thanks!

**Comment by willingc** [comment]
@ehashman Thanks for reviewing. :cookie: 
@waseem18 Thanks for contributing the PR. Happy it has been merged. :penguin:

**Pull request merged**
