### PR TITLE
Issue #1553 Fixed css styles in bug tracker

### PR DESCRIPTION
**Pull request by jul-k**

### CODE REVIEW

**Comment by jul-k** [comment]
Guys do you know what's wrong with Travis?

**Comment by willingc** [comment]
@jul-k Thanks for the PRs. :sunglasses: 

Travis has been a little wonky when downloading and installing packages the past few days. You can click on the build details in Travis and it will show you the actual command line results of the builds.

I resubmitted this PR to Travis to rebuild.

**Comment by jul-k** [comment]
You are welcome! ;-)

**Comment by paulproteus** [comment]
Hi @albertyw -- this might be a good bit of OpenHatch code that can be reviewed.

Some pointers on OpenHatch code review:

* Contributor's guide -- https://openhatch.readthedocs.org/en/latest/getting_started/index.html -- this includes things like how the docs work and how to run the test suite.

* Do take a look at the "Key Features of openhatch.org" -- that should give you a sense of what the site actually does.

* When you run the codebase, you don't necessarily need to create a virtualenv; for better or for worse, the codebase bundles all its dependencies.

If you can review this and leave a comment indicating if you think it's worth merging, or what changes you think are necessary, that'd be so extraordinarily helpful. Code review is a major bottleneck for the project, and I'd love to be able to merge all the various contributors' code faster.

If you conclude this deserves a positive review, I'll do a meta-review and then probably merge it. (And feel free to leave whatever useful feedback you think is sensible!)

**Comment by albertyw** [comment]
@jul-k @willingc The travis errors probably came from github being DDOSed.  Looks like the travis tests are passing now.

**Comment by albertyw** [comment]
After those two fixes, this PR looks good :cake:

**Comment by paulproteus** [comment]
Hi all!

I'll merge this as-is now, to minimize latency; @jul-k , thanks hugely for this change. If you want to take a look at @albertyw 's questions and see if they would make for a good follow-up pull request, that would be splendid.

Also @jul-k , please send a licensing statement to the email list, per https://openhatch.readthedocs.org/en/latest/getting_started/handling_contributions.html#permit-us-to-share-your-work

Thanks and I hope to continue to see you around the project!

**Pull request merged**
