### PR TITLE
Fixed some typos in documentation

### PR DESCRIPTION
**Pull request by codeaditya**

### CODE REVIEW

**Comment by Deborah-Digges** [comment]
Thanks for the contibution, @codeaditya :penguin: 
Please do send an email to permit us to use your work if you haven't done so already https://openhatch.readthedocs.org/en/latest/getting_started/handling_contributions.html#permit-us-to-share-your-work

**Comment by Deborah-Digges** [comment]
A general tip: Use the imperative mood in the subject line of your commit message. For example, "Fix some typos... " instead of "Fixed some typos.. ". 
Do read more here: http://chris.beams.io/posts/git-commit/

**Comment by ehashman** [comment]
LGTM!

**Comment by codeaditya** [comment]
Thanks @Deborah-Digges. I have sent the email granting permission to re-use the work. And, the link you provided for writing commit messages was very good. I would try to inculcate the habit from now onwards for all my commit messages.

**Comment by codeaditya** [comment]
Thanks @ehashman. That was fast :)

**Comment by ehashman** [comment]
No problem, @codeaditya!

**Pull request merged**
