### PR TITLE
Rewritten commits to help with git issues for PR #1555, closes #1550

### LINKED ISSUE #1550: "Maintainer updates box"  opens up and get stacked vertically after clicking (explain this) link
While filling out the form for adding your project when you click on the "(explain this)" link of the "Receive maintainer update" checkbox the box opens up showing the info related to it. If you again click on the link a next box pops up and get stacked vertically below the first box and so on it continues the number of time you click on link.
You can reproduce the bug as:

1) login to your profile

2) Click on add a project until you get the form which you fill out for adding the project.

3) Click on (explain this) link of Receive maintainer update. You will get a JS Box explaining what is maintainer updates.

4)The number of time you click explain this link that number of times this Maintainer updates box opens up and get stacked vertically.and even the closeall button is not visible once the number goes beyond 3.

### PR DESCRIPTION
**Pull request by ehashman**
@shriyanka, let me know if you'd like me to change anything!

### CODE REVIEW

**Comment by ehashman** [comment]
(note to self, I tried to reproduce these commits as they were without all the extraneous merges, but I think I should squash them down further. @shriyanka, any objection to that? The PR will then end up as two commits, one for each file.)

**Comment by shriyanka** [comment]
@ehashman  no objections you can proceed further for best :) 
@onceuponatimeforever  asked to make some changes in the doc file of  for issue #1338 on the PR i submitted. Do I have to do the changes?

**Comment by phildini** [comment]
I think @shriyanka is talking about some slightly odd capitalization that @onceuponatimeforever pointed out to fix. I'm 50/50 on fixing before merging. Does @ehashman or @paulproteus have an opinion?

**Comment by paulproteus** [comment]
If there's confusion about next steps, I say merge it and file a separate
issue.

**Comment by ehashman** [comment]
Ahh okay I guess this is merged.

**Pull request merged**
