### PR TITLE
Remove remaining dia references

### PR DESCRIPTION
**Pull request by willingc**
Removes a few references to DIAs left in code after PR #1508.

### CODE REVIEW

**Comment by ehashman** [comment]
Yay code deletions!!

**Comment by ehashman** [comment]
And speaking of the devil, I just ran into this: http://openhatch.org/+meta/

Not sure where this code lives; perhaps a look at inside.openhatch.org would help?

**Comment by paulproteus** [comment]
For what it's worth:

➜  oh-mainline git:(master) python manage.py shell

​In [5]: django.core.urlresolvers.resolve('/+meta/')
Out[5]: ResolverMatch(func=<function meta at 0x7f9e6d65f758>, args=(),
kwargs={}, url_name='mysite.base.views.meta', app_name='None', namespace='')

That is to say:

It lives in mysite/views/meta in a function called meta!

**Comment by willingc** [comment]
@paulproteus Cool tip! I didn't think of using the shell, but it's very helpful. If you have a minute will you  give PR #1544 a scan, it's short. Just wanted your feedback on it. Thanks :)

**Pull request merged**
