### PR TITLE
added a new section to basic testing documentation #1479

### PR DESCRIPTION
**Pull request by vipul-sharma20**
Added a new section in "Testing Basics" titled, "Controlling detail of test output" and specified the use of  `--verbosity`/  `-v` to get  more descriptive output.

### CODE REVIEW

**Comment by paulproteus** [comment]
Huge props to both of you, @willingc and @vipul-sharma20 !

**Comment by willingc** [comment]
@vipul-sharma20 I'm happy to merge this helpful documentation addition to the Basic Testing section. Nice work and thanks for your patience on the other pull requests. :cake:

**Comment by vipul-sharma20** [comment]
Thanks for the acknowledgement :) feels nice. I will continue to try my best to contribute to OpenHatch.

**Comment by ehashman** [comment]
+1!

**Pull request merged**
