### PR TITLE
add alt tags to profile pictures

### PR DESCRIPTION
**Pull request by sidwatal**
Alt tags for profile pictures and default profile pics

### CODE REVIEW

**Comment by phildini** [comment]
This is so close to being amazing. Would you mind using the user's name in the alt text? eg, "Profile picture for { username }?" 

Alt text is a major accessibility win, and I'll happily accepts PRs improving accessibility. If you don't want to adjust it, let me know and I'll merge as is.

**Comment by sidwatal** [comment]
Doing this now.

**Comment by phildini** [comment]
To people with screenreaders, "Profile picture for Username" will be more informative that "Profile picture for user"

You should use the template variable syntax to replace username with the actual username from the object.

**Comment by phildini** [comment]
it's probably going to be `{% answer.author.[username variable name] %}` or something.

**Comment by sidwatal** [comment]
Changed it to username. Wasn't sure about template variable syntax. Sorry if this is wrong. I came across this repo during an open source contribute-athon and am a rank beginner at web-development. But if there is anything else I could help with, let me know.

**Comment by phildini** [comment]
Thanks for being so flexible! I think if we're not going to do the variable substitution at this time (which is totally ok) we should leave it as you had it originally and just use "user"

**Pull request merged**
