### PR TITLE
Replace PIL with pillow in requirements

### LINKED ISSUE #1698: Update PIL requirement to pillow
PIL is no longer actively maintained. Pillow is a fork of PIL that is actively maintained and implements the PIL API.

Recommend updating ``requirements.txt`` to ``pillow``.

### PR DESCRIPTION
**Pull request by willingc**
Fixes #1698

### CODE REVIEW

**Comment by paulproteus** [comment]
+0

FWIW the only deployment that uses `requirements.txt` is the Heroku deploy setup. So I'd appreciate Carol if you can test that the code deploys correctly on Heroku and that manipulating images seems to work.

If so, +1.

**Comment by willingc** [comment]
@paulproteus I didn't know that only the Heroku deploy used ``requirements.txt``. Happy to test it but I'm not sure how to deploy and test on Heroku. Should I deploy and test on my Heroku account or ...?

**Comment by paulproteus** [comment]
Yeah -- you can do a test deploy on your own Heroku account, and then test that image uploading works. The OpenHatch docs contain info on doing a Heroku deployment.

and/or we could wait to deploy this until the Heroku cut-over has completed, since John Morrissey thinks it'll happen soon, and then we can use the live deployment to make sure this works OK. I think testing this kind of pull request on the live site is honestly pretty OK.

**Comment by willingc** [comment]
Let's leave this until after the Heroku / Postgres goodness happens :cake:

**Comment by jwm** [comment]
@willingc I grabbed this as part of the Heroku deployment cut in #1590.

**Comment by willingc** [comment]
Cool. Thanks @jwm.

**Pull request closed without merging**
