### PR TITLE
change "expand" to "collapse" when a bug is expanded and vice versa

### PR DESCRIPTION
**Pull request by vipul-sharma20**

### CODE REVIEW

**Comment by willingc** [comment]
This PR needs review. It addresses issue #1536.

**Comment by ehashman** [comment]
I feel like it would be better to swap "expand" with "collapse" in the same function that expands/collapses each bug, as opposed to adding a new, separate function to search the page and replace the text.

**Comment by onceuponatimeforever** [comment]
I agree with @ehashman's suggestion. Much easier to change the css or html directly than to have to maintain a script that edits the static files.

**Comment by ehashman** [comment]
Because there's been no activity on this PR for about a month and Susan and I suggested an alternate fix, I am going to close this and recommend you submit a new PR implemented as suggested, @vipul-sharma20.

**Pull request closed without merging**
