### PR TITLE
Remove bottom specification for footer

### LINKED ISSUE #1599: Footer floating over text in live environment
A recent change has broken the footer so that it now floats over the text of the page. A quick looks indicates it's on every page. On Firefox 37.0.1 and Chrome 41.0.2272.118 - OSX 10.9.5 I see the following:

footer-bug

Curiously, I can't entirely recreate this bug locally. Although I can see an issue with the footer floating off-center. As seen here:

local-footer-bug

Which I've identified as stemming from commit 1fa255d520f1a48316f2065cffbd8c265c2e0143. No idea yet why I can't entirely recreate it (I've cleared my browser cache etc.).

### PR DESCRIPTION
**Pull request by ableman**
*Fixes #1599
*If anyone can test this to make sure it works, or explain why it works to me, that would be great

### CODE REVIEW

**Comment by phildini** [comment]
Since we've had some trouble with the footer this week, can we get some screenshots of the what things look like now? Preferably on multiple pages?

**Comment by ableman** [comment]
Here are all the pages where I've been able to spot the problem, all for live site

image

image

image

image

**Comment by phildini** [comment]
Thanks for responding! I realize I should have been more clear. Could we get screenshots of those same pages on your dev server, with your fix applied?

**Comment by ableman** [comment]
Certainly :)

image

image

image

image

**Comment by phildini** [comment]
Oh hey that looks great! I think this is ready to merge, but you could really convince me by showing me a different browser (like firefox) to prove the same behavior.

**Comment by ableman** [comment]
Before:
image

After:
image

**Comment by paulproteus** [comment]
I'll merge it!!

**Pull request merged**
