### PR TITLE
IRC mission

### PR DESCRIPTION
**Pull request by ehashman**
I want to create this pull request (as per #711) because it appears to have been totally forgotten about but this code is still happily sitting around, over 500 commits later!

### CODE REVIEW

**Comment by phildini** [comment]
This is amazing.

It also makes me wish there was a way to only see changes not in /vendor.

**Comment by phildini** [comment]
Looking at this in more depth, I'm very tempted to say :ship:. Do you know what the merge conflict is?

**Comment by ehashman** [comment]
This is an 11k LOC PR so I'd like to look at it in some depth before merging. I plan on doing a good amount of testing and then doing the merge manually (and probably fixing the conflicts in /vendor) if we want to keep this. Still super thrilled that I managed to find an untouched PR from August 2010!

**Comment by willingc** [comment]
@ehashman You are so :penguin: open-hatchy :)

**Comment by ehashman** [comment]
I'm going to assign this to me but if someone else gets around to it before me, feel free to pick this up.

**Comment by willingc** [comment]
@paulproteus and @ehashman: So I was going to be a good samaritan and bring this mission up to date. I wound up doing a merge commit instead of just commiting the changes that I had made so far. 

I will need help reverting this or we can open a new issue to fix the front end which is not displaying yet. The code is up to date and passes all tests. I did not deploy this yet if that helps.

Ugh...I am going to slink back into my GitHub pit until someone with more git magic than me can talk me through what would be best to do with this. I'm sorry for messing this up.

**Comment by paulproteus** [comment]
Oh, interesting, OK. So it sounds like you've merged this code but didn't
mean to? Reverting a merge commit is possible.

http://www.christianengvall.se/undo-pushed-merge-git/ talks about how.

I am AFK a little bit, but can attempt to look into this instead if you
prefer.

**Comment by ehashman** [comment]
I am assuming we are okay with leaving this merged and slowly fixing this for now?

It doesn't appear to have been deployed... or at least, I'm not seeing it listed on the production `missions/` page.

**Pull request merged**
