### PR TITLE
Add codecov

### PR DESCRIPTION
**Pull request by willingc**
This is an initial PR to add codecov service to oh-mainline.

### CODE REVIEW

**Comment by willingc** [comment]
@ehashman @paulproteus PR is ready for review :)

**Comment by paulproteus** [comment]
Quick question - how is this better than coveralls?

**Comment by paulproteus** [comment]
Which I mean in a warm-hearted curious way, rather than a dismissive way!

**Comment by willingc** [comment]
Closes #1687

**Comment by willingc** [comment]
Hey @paulproteus, I missed these earlier questions. I think it codecov.io complements coveralls. One of the things that I like about codecov.io is that it can provide the contributor some detailed feedback in a PR on what can be improved and how their code changes impacted coverage. I also found their reports fairly customizable and user friendly which is helpful for new contributors. I suggest keeping both coveralls and codecov.io :)

**Comment by paulproteus** [comment]
+1

**Pull request merged**
